// Package codecs provides implementations of different codecs
// using different serialization formats for go. All implementation
// follow the interface generated by the rpkit code generator.
package codecs

// Encoder defines an interface representing a generic encoder which
// expects a interface{} type has it's encoding target.
//type Encoder interface {
//	Encode(context.Context, io.Writer, interface{}) error
//}

// Decoder defines an interface representing a generic decoder which
// returning a interface{} type has it's response.
//type Decoder interface {
//	Decode(context.Context, io.Reader) (interface{}, error)
//}

// TargetDecoder defines an interface representing a target decoder which
// expects a type to decode into.
//type UnmarshalDecoder interface {
//	Decode(context.Context, io.Reader, interface{}) error
//}
