// Package codecs provides implementations of different codecs
// using different serialization formats for go. All implementation
// follow the interface generated by the rpkit code generator.
package codecs
